contents:
  repositories:
    - http://dl-cdn.alpinelinux.org/alpine/edge/main
  packages:
    - ca-certificates-bundle
    - alpine-baselayout-data
    - iptables

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: 65532

os-release:
  id: alpine
  version-id: '3.16.0'
  name: 'Alpine iptables'
  pretty-name: 'Alpine iptables (apko)'
