on:
  push:
    branches:
      - main
      - trivy
  schedule:
    - cron: '0 0 * * *'

name: Create Release

jobs:
  build:
    name: Release OCI image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - uses: imjasonh/setup-crane@v0.1

    - uses: distroless/actions/apko-snapshot@main
      id: apko-snapshot
      with:
        config: .apko.yaml
        base-tag: ghcr.io/${{ github.repository }}

#     - run: |
#         echo "${{ github.token }}" | crane auth login ghcr.io --username "${{ github.actor }}" --password-stdin
#         crane cp nginx:alpine ghcr.io/${{ github.repository }}:bad

    - uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.apko-snapshot.outputs.digest }}
        format: 'table'
        exit-code: '1'
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
