on:
  push:
    branches:
      - main
      - trivy
  schedule:
    - cron: '0 0 * * *'

name: Create Release

jobs:
  build:
    name: Release OCI image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - uses: imjasonh/setup-crane@v0.1

    - name: "whatever"
      shell: bash
      run: |
        echo '${{ toJson(github) }}'

    - uses: mattmoor/actions-2/apko-snapshot@trivy-attest
      id: apko-snapshot
      with:
        config: .apko.yaml
        base-tag: ghcr.io/${{ github.repository }}
